repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff-sort
        name: ruff-sort
        entry: ruff check --select I --fix
        require_serial: true
        language: system
        types: [python]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        require_serial: true
        language: system
        types: [python]

      - id: ruff-check
        name: ruff-check
        entry: ruff check .
        require_serial: true
        language: system
        types: [python]

exclude: "^natspec/.*"
