name: Other tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
  
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: npm install -g ganache@7.5.0
    
    - name: Run project unit tests 
      run: |
        brownie networks add development ganache-mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork="https://eth-mainnet.g.alchemy.com/v2/$ALCHEMY_KEY" accounts=10 mnemonic=brownie port=8545 timeout=120
        brownie test tests/test_collateral_* tests/test_cryptopunks_vault_core.py tests/test_lendingpool_* tests/test_liquidations_* tests/test_loans_core.py --durations=20 --network ganache-mainnet-fork


